source: "app"
destination: "dist"
exclude:
  - "styles"
  - "css"
prose:
  rooturl: 'app'
  ignore:
    - 'robots.txt'
    - 'favicon.ico'
    - '_includes'
    - '_layouts'
    - 'scripts'
    - 'styles'
