version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.2.7-node
    working_directory: ~/repo
    environment:
    steps:
      - checkout
      - run: npm install
      - run: npm install
      - deploy:
          name: deploy to AWS
          command: bundle exec s3_website push
