version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node
    working_directory: ~/repo
    environment:
    steps:
      - checkout
      - run: bundle install
      - run: sudo apt-get update -y
      - run: sudo apt-get install --assume-yes openjdk-8-jre
      - run: npm install
      - run: npm run pretest
      - deploy:
          name: deploy to AWS
          command: s3_website push
