version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.2.7-node
    working_directory: ~/repo
    environment:
    steps:
      - checkout
      - run: bundle install
      - run: apt-get install --assume-yes openjdk-7-jre
      - run: npm install
      - run: npm run pretest
      - deploy:
          name: deploy to AWS
          command: s3_website push
